services:
  - type: web
    name: billiard-api
    runtime: node
    rootDir: server
    buildCommand: npm install && ./node_modules/.bin/prisma generate --schema=./prisma/schema.prisma && npm run build
    startCommand: ./node_modules/.bin/prisma migrate deploy --schema=./prisma/schema.prisma && npm run start
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
databases:
  - name: billiard-db
    databaseName: billiard_club
    user: billiard
    plan: free