services:
  - type: web
    name: billiard-api
    runtime: node
    rootDir: server
<<<<<<< HEAD
    buildCommand: npm install && npx prisma generate --schema=./prisma/schema.prisma && npm run build
    startCommand: npx prisma migrate deploy --schema=./prisma/schema.prisma && npm run start
=======
buildCommand: npm install && npx prisma generate --schema=./prisma/schema.prisma && npm run build
startCommand: npx prisma migrate deploy --schema=./prisma/schema.prisma && npm run start
>>>>>>> dca06c1239a7913b00c2824b670a1ff59d5ccbf0
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
databases:
  - name: billiard-db
    databaseName: billiard_club
    user: billiard
    plan: free