-- AlterTable
ALTER TABLE "BusinessSettings" ADD COLUMN     "dayHourlyPrice" DOUBLE PRECISION NOT NULL DEFAULT 40000,
ADD COLUMN     "dayStartTime" TEXT NOT NULL DEFAULT '06:00',
ADD COLUMN     "nightHourlyPrice" DOUBLE PRECISION NOT NULL DEFAULT 50000,
ADD COLUMN     "nightStartTime" TEXT NOT NULL DEFAULT '18:00';
